#!/bin/sh

# https://zulu.org/api/#query-parameters

# set -ex

arch=x86
hwbit=64
os=linux
jdk_version=0
feature=fx,headfull
bundle_type=jdk
ext=tar.gz

test 'Darwin' = "`uname -s`" && os=macos


ls_remote() {
    url="https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?jdk_version=${jdk_version}&os=${os}&arch=${arch}&hw_bitness=${hwbit}&ext=${ext}&bundle_type=${bundle_type}&javafx=true&release_status=ga"
    curl -s "$url" | jq -r '.url'
}


jdk_version=11  ls_remote
jdk_version=''  ls_remote
