#!/usr/bin/env bash
# convert markdown to (google's) html5slides
# '---' should be put between each slide

print_head() {
  cat << EOL
<html>
  <head>
    <title>Presentation</title>
    <meta charset='utf-8'>
    <script src='http://html5slides.googlecode.com/svn/trunk/slides.js'></script>
  </head>
  <style>
    /* Your individual styles here, or just use inline styles if that’s
       what you want. */
  </style>
  <body style='display: none'>
    <section class='slides layout-regular'>

<article>
EOL
}

print_foot() {
  cat << EOL
</article>
    </section>
  </body>
</html>
EOL
}


main() {
  local mdFile="$1"
  local outputHtml=${mdFile%%.md}.html

  local MARKDOWN_BIN

  # perl markdown
  which markdown &> /dev/null
  if [ '0' = "$?" ]; then
    MARKDOWN_BIN=`which markdown`
  fi
  # python markdown2 pip
  which markdown_py2 &> /dev/null
  if [ '0' = "$?" ]; then
    MARKDOWN_BIN=`which markdown_py2`
  fi
  # python markdown2 arch
  which markdown_py &> /dev/null
  if [ '0' = "$?" ]; then
    MARKDOWN_BIN=`which markdown_py`
  fi

  if [ -f $mdFile ]; then
    rm -f $outputHtml
    touch $outputHtml

    print_head >> $outputHtml
    $MARKDOWN_BIN $mdFile >> $outputHtml
    print_foot >> $outputHtml

    sed -i 's/<hr\ \/>/<\/article><article>/' $outputHtml

    echo "[$outputHtml] done, now get assets from http://code.google.com/p/html5slides/"
  else
    echo "$mdFile doesn't exist"
    exit 1
  fi
}

main $@
