#!/usr/bin/env bash
# ClusterSSH needs X, tmux comes to rescue

check_inside_tmux()
{
  if [ -z "$TMUX" ]; then
    echo 'Please run the command in tmux session'
    exit -1;
  fi
}

main()
{
  check_inside_tmux

  # already in a tmux session, won't need to specify session
  #TMUXSESSION=`echo $TMUX | awk -F, '{ print $3 }'`

  # create new window which will contain all the ssh sessions
  tmux new-window
  local TMUXWINDOW=`tmux list-window | awk -F: '/(active)/ { print $1 }'`


  # split window and `ssh` to `host`
  for host in "$@"; do
    tmux split-window -t $TMUXWINDOW
    tmux send-key -t $TMUXWINDOW "ssh $host" Enter
  done

  # kill the first pane
  tmux kill-pane -t "${TMUXWINDOW}.0"
  tmux select-layout -t $TMUXWINDOW tiled
  tmux set-window-option -t $TMUXWINDOW synchronize-panes on
}

main $@
