#!/usr/bin/env bash
# ClusterSSH needs X, tmux comes to rescue

check_inside_tmux()
{
  if [ -z "$TMUX" ]; then
    echo 'Please run the command in tmux session'
    exit -1;
  fi
}

main()
{
  check_inside_tmux

  local SSH_CMD='ssh'
  local charset=''

  while getopts "c:" OPTION
  do
    case $OPTION in
      c)
        charset=$OPTARG
        ;;
    esac
  done

  if [ -n "$charset" ]; then
    SSH_CMD="luit -encoding $charset ssh"
    shift;shift;
  fi

  # already in a tmux session, won't need to specify session
  #TMUXSESSION=`echo $TMUX | awk -F, '{ print $3 }'`

  # create new window which will contain all the ssh sessions
  tmux new-window
  local TMUXWINDOW=`tmux list-window | awk -F: '/(active)/ { print $1 }'`


  # split window and `ssh` to `host`
  for host in "$@"; do
    tmux split-window -t $TMUXWINDOW
    local TMUXPANE=`tmux list-panes -t $TMUXWINDOW | awk -F: 'END { print $1 }'`
    tmux send-key -t "${TMUXWINDOW}.${TMUXPANE}" "$SSH_CMD $host" Enter
    tmux select-layout -t $TMUXWINDOW even-vertical > /dev/null
  done

  # kill the first pane
  tmux kill-pane -t "${TMUXWINDOW}.0"
  tmux set-window-option -t $TMUXWINDOW synchronize-panes on > /dev/null
  sleep 1s && tmux select-layout -t $TMUXWINDOW even-vertical > /dev/null
}

main $@
