#!/bin/bash

INP="$1"

which sha256sum > /dev/null && SHA256SUM=`which sha256sum`
which gsha256sum > /dev/null && SHA256SUM=`which gsha256sum`

HASH=$(echo "${INP}`cat $HOME/.salt`" | $SHA256SUM)

echo ${HASH:1:10}

