#!/usr/bin/env bash

for x in *; do
  if [ -d $x/.git ]; then
    echo $x
    echo ">>>>>> GC [$x]"
    eval "pushd '$x' > /dev/null"
    git gc --auto --prune=now
    git prune
    rm -rf .git/objects/pack/tmp_pack_*
    # git clean -xdf
    popd > /dev/null
  fi
done

