#!/bin/sh

# parallel -j 10 repo_fetch

echo "-> $1"
cd $1


test -d .git && timeout 30s git fetch --all --prune && rm -f .git/objects/pack/tmp_pack_* && git gc --auto
test -d .hg  && timeout 30s hg pull
