#!/bin/sh

if [ -d $x/.git ]; then
  echo ">>>>>> GC [$x]"
  eval "pushd '$x' > /dev/null"
  # git prune
  git gc --auto --prune=now
  rm -rf .git/objects/pack/tmp_pack_*
  # git clean -xdf
  popd > /dev/null
fi
