#!/usr/bin/env bash

for d in *; do
  echo '>>>' $d
  pushd "$d" > /dev/null

  if [ -d .git ]; then
    if [ -n "`cat .git/config | grep '\[svn\-remote'`" ]; then
      echo '=git-svn' $d `git config --get 'svn-remote.svn.url'`
    else
      while read line; do
        echo '=git' $d $line
      done < <(git remote -v)
    fi
  elif [ -d .hg ]; then
    echo '=hg' $d `hg paths`
  else
    echo '=unknown' $d
  fi

  popd > /dev/null
done
