#!/bin/sh

skipping=false
until=''
if [ -n "$1" ]; then
    until="$1"
    skipping=true
fi

for d in *; do
    if [ "$skipping" = true ]; then
        if [ "$until" != "$d" ]; then
            continue
        fi
        skipping=false
    fi

    pushd "$d" > /dev/null
    echo ">>> $d"

    if [ -d ".git" ]; then
        git fetch --prune --all
        if [ -n "`cat .git/config | grep '\[svn\-remote'`" ]; then
            git svn fetch
        fi
        rm -rf .git/objects/pack/tmp_pack_*
    elif [ -d ".hg" ]; then
        hg pull
    fi

    popd > /dev/null
done
