#!/bin/sh

for d in *; do
    if [ -d $d/.git ]; then
        n=`find $d/.git/objects -type f | grep -v 'pack$' | grep -v 'idx$' | wc -l`
        # # test $n -gt 0 && echo "[$d] found $n"
        test $n -gt 20 || continue

        echo "[GC] $d $n"
        pushd $d > /dev/null
        git gc
        # git gc --auto --prune=now
        # git gc --auto
        popd > /dev/null
        sleep 1s
    fi
done

