#!/usr/bin/env bash


ICMP_DEST='199.59.150.7' # twitter.com
#ICMP_DEST='199.59.150.99' # unreachable for testing

ICMP_COUNT=3
ICMP_TIMEOUT=3

LOG_FILE='/tmp/vpncwatch.log'


test_icmp()
{
  # timeout 4 sec, try 3 times
  ping -W $ICMP_TIMEOUT -c $ICMP_COUNT $ICMP_DEST &> /dev/null
  echo $?
}

reconnect()
{
  echo "`date`   *** reconnect" >> $LOG_FILE
  vpnc-disconnect
  vpnc
}

do_watch()
{
  test -n `pidof vpnc` || exit 1
  test 0 = `test_icmp` || reconnect
}

main()
{
  if [ -z $_BACKGROUND ]; then
    (_BACKGROUND=1 exec $0 &> /dev/null &)&
    exit 0
  fi

  touch $LOG_FILE

  while true; do
    do_watch
    sleep 5s
  done
}

main $@

