name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go version
      - run: mkdir out
      - run: go build -o out/goecho             ./goecho.go
      - run: go build -o out/tls-cert-check     ./tls-cert-check.go 
      - run: pushd gitlab-cli && go build && mv gitlab ../out && popd
      - run: pushd cfupdate && go build && mv cfupdate ../out && popd
      - uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: out

